// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/promise/all dojo/Deferred dojo/json dojo/i18n!../nls/strings ./util esri/lang esri/request esri/arcgis/utils esri/layers/ArcGISDynamicMapServiceLayer esri/layers/ArcGISImageServiceLayer esri/layers/ArcGISTiledMapServiceLayer esri/layers/DynamicLayerInfo esri/layers/FeatureLayer esri/layers/ImageParameters esri/layers/ImageServiceParameters esri/layers/KMLLayer esri/layers/LayerDrawingOptions esri/layers/MosaicRule esri/layers/RasterFunction esri/layers/RasterXLayer esri/layers/TileInfo esri/layers/VectorTileLayer esri/layers/WFSLayer esri/layers/WMSLayer esri/layers/WMSLayerInfo esri/layers/WMTSLayer esri/layers/WMTSLayerInfo esri/layers/WebTiledLayer esri/dijit/PopupTemplate esri/InfoTemplate esri/renderers/jsonUtils esri/geometry/Extent esri/SpatialReference jimu/utils".split(" "),
function(L,B,r,M,E,t,y,F,G,l,w,N,O,P,H,Q,I,R,S,T,U,V,W,X,Y,Z,aa,ba,ca,ia,ja,da,z,ea,J,C,fa,ha){return L(null,{item:null,itemUrl:null,map:null,serviceUrl:null,constructor:function(a){B.mixin(this,a)},addItem:function(a,b){var c=new t;this.map=b;this.item=a;this.itemUrl=this._checkMixedContent(a.itemUrl);this.serviceUrl=this._checkMixedContent(a.url);if("Feature Service"===a.type)return this._addFeatureService();if("Image Service"===a.type)return this._addImageService();if("KML"===a.type)return this._addKML();
if("Map Service"===a.type)return this._addMapService();if("Vector Tile Service"===a.type)return this._addVectorTileService();if("WFS"===a.type)return this._addWFS();if("WMS"===a.type)return this._addWMS();if("WMTS"===a.type)return this._addWMTS();console.warn("Unsupported item type: ",a.type);c.resolve(null);return c},_addFeatureService:function(){var a=this,b=new t,c=this.serviceUrl,e=this.item,g={},d=null,h=[],m=[],f=[];a._readItemJsonData().then(function(k){(g=k||{},g.layers)&&0<g.layers.length&&
r.forEach(g.layers,function(p){"undefined"!==typeof p.id&&null!==p.id&&(null===d&&(d=[]),d.push(p.id))});return a._readRestInfo(c)}).then(function(k){if(!k||"string"!==typeof k.type||"Feature Layer"!==k.type&&"Table"!==k.type){var p=[];k&&k.layers&&0<k.layers.length&&r.forEach(k.layers,function(q){p.push(q)});k&&k.tables&&0<k.tables.length&&r.forEach(k.tables,function(q){p.push(q);h.push(q.id)});0<p.length?r.forEach(p,function(q){var u=!0;-1===h.indexOf(q.id)&&null!==d&&0<d.length&&(u=r.some(d,function(n){return n===
q.id}));u&&(u=new I(c+"/"+q.id,{id:a._generateLayerId(),outFields:["*"]}),m.push(a._waitForLayer(u)))}):console.warn("No layers or tables...")}else k=new I(c,{id:a._generateLayerId(),outFields:["*"]}),m.push(a._waitForLayer(k));return E(m)}).then(function(k){r.forEach(k,function(p){f.push(p)});f.reverse();return f}).then(function(){r.forEach(f,function(k){var p=a._processFeatureLayer(k,e,g);k.arcgisProps={title:p.title};k._titleForLegend=p.title;l.isDefined(k.title)||(k.title=p.title);a._addLayer(k)})}).then(function(){b.resolve(f)}).otherwise(function(k){b.reject(k)});
return b},_addImageService:function(){var a=this,b=new t;a._readItemJsonData().then(function(c){return a._newImageServiceLayer(c||{})}).then(function(c){a._addLayer(c);b.resolve(c)}).otherwise(function(c){b.reject(c)});return b},_addKML:function(){var a=this,b=new t;a._newKMLLayer().then(function(c){c&&(c.title=a.item.title);a._addLayer(c);b.resolve(c)}).otherwise(function(c){b.reject(c)});return b},_addMapService:function(){var a=this,b=new t;a._readItemJsonData().then(function(c){return a._newMapServiceLayer(c||
{})}).then(function(c){a._addLayer(c);b.resolve(c)}).otherwise(function(c){b.reject(c)});return b},_addVectorTileService:function(){var a=this,b=new t;a._newVectorTileLayer().then(function(c){a._addLayer(c);b.resolve(c)}).otherwise(function(c){b.reject(c)});return b},_addWFS:function(){var a=this,b=new t;a._readItemJsonData().then(function(c){return a._newWFSLayer(c||{})}).then(function(c){c&&(c.title=a.item.title);a._addLayer(c);b.resolve(c)}).otherwise(function(c){console.log("Error adding WFS",
c);b.reject(c)});return b},_addWMS:function(){var a=this,b=new t;a._readItemJsonData().then(function(c){return a._newWMSLayer(c||{})}).then(function(c){c&&(c.title=a.item.title);a._addLayer(c);b.resolve(c)}).otherwise(function(c){b.reject(c)});return b},_addWMTS:function(){var a=this,b=new t;a._readItemJsonData().then(function(c){return a._newWMTSLayer(c||{})}).then(function(c){c&&(c.title=a.item.title);a._addLayer(c);b.resolve(c)}).otherwise(function(c){b.reject(c)});return b},_addLayer:function(a){var b=
this.item;a&&(a.xtnItemId=b.id,a.xtnAddData=!0,!a.arcgisProps&&b&&(a.arcgisProps={title:b.title},a._titleForLegend=b.title),l.isDefined(a.title)||(a.title=b.title),a._wabProperties={itemLayerInfo:{itemId:b.id,itemUrl:this.itemUrl,portalUrl:b.portalUrl}},this.map.addLayer(a))},_checkMixedContent:function(a){return G.checkMixedContent(a)},_checkUrl:function(a){return N._checkUrl(a)},_checkVectorTileUrl:function(a,b){var c=new t;if(function(g,d){return-1!==g.indexOf(d,g.length-d.length)}(a,".json"))return b.styleUrl=
a,c.resolve(a),c;var e={url:null,content:{},handleAs:"json",callbackParamName:"callback"};this.itemUrl?(e.url=this.itemUrl+"/resources/styles/root.json",w(e,{}).then(function(){b.styleUrl=e.url;c.resolve(e.url)}).otherwise(function(){e.url=a+"/resources/styles/root.json";w(e,{}).then(function(){b.styleUrl=e.url;c.resolve(e.url)}).otherwise(function(){b.url=a;c.resolve(a)})})):(e.url=a+"/resources/styles/root.json",w(e,{}).then(function(){b.styleUrl=e.url;c.resolve(e.url)}).otherwise(function(){b.url=
a;c.resolve(a)}));return c},_generateLayerId:function(){return this._generateLayerIds(1)[0]},_generateLayerIds:function(a){var b,c=[];for(b=0;b<a;b++)c.push(this._generateRandomId());return c},_generateRandomId:function(){var a=null;a="function"===typeof Date.now?Date.now():(new Date).getTime();var b=(""+Math.random()).replace("0.","r");return(a+""+b).replace(/-/g,"")},_makeFeatureLayerTitle:function(a,b,c){try{if(b&&c&&b===c)return b;if(b&&c){var e=c.indexOf(b);if(0===e){var g=c.substring(e+b.length+
1);if(13<=g.length){var d=/^\d+$/;if(d.test(g))return b}}}}catch(h){}return a.replace("{serviceName}",b).replace("{layerName}",c)},_newImageServiceLayer:function(a){var b=new t,c=this._generateLayerId(),e=this.serviceUrl,g=this.serviceUrl,d={mapLayerId:c,bandIds:null,format:null,compressionQuality:null,opacity:1,visibility:!0};l.isDefined(a.visibility)&&!1===a.visibility&&(d.visibility=!1);l.isDefined(a.opacity)&&(d.opacity=a.opacity);l.isDefined(a.minScale)&&!l.isDefined(d.minScale)&&(d.minScale=
a.minScale);l.isDefined(a.maxScale)&&!l.isDefined(d.maxScale)&&(d.maxScale=a.maxScale);l.isDefined(a.refreshInterval)&&!l.isDefined(d.refreshInterval)&&(d.refreshInterval=a.refreshInterval);!a.popupInfo||d.popupInfo||d.disablePopup||(d.popupInfo=a.popupInfo);a.renderingRule&&!d.renderingRule&&(d.renderingRule=a.renderingRule,a.renderingRule.functionName&&(d.renderingRule.rasterFunction=a.renderingRule.functionName));a.bandIds&&!d.bandIds&&(d.bandIds=a.bandIds);a.mosaicRule&&!d.mosaicRule&&(d.mosaicRule=
a.mosaicRule);a.format&&!d.format&&(d.format=a.format);l.isDefined(a.compressionQuality)&&!l.isDefined(d.compressionQuality)&&(d.compressionQuality=a.compressionQuality);!a.layerDefinition||!a.layerDefinition.definitionExpression||l.isDefined(d.layerDefinition)&&l.isDefined(d.layerDefinition.definitionExpression)||(d.layerDefinition=d.layerDefinition||{},d.layerDefinition.definitionExpression=a.layerDefinition.definitionExpression);a=new S;null!==d.bandIds&&(a.bandIds=d.bandIds);null!==d.format&&
(a.format=d.format,null!==d.compressionQuality&&(a.compressionQuality=d.compressionQuality));if(d.renderingRule&&d.renderingRule.rasterFunction){var h=new W(d.renderingRule);a.renderingRule=h}d.mosaicRule&&(h=new V(d.mosaicRule),a.mosaicRule=h);l.isDefined(d.noData)&&(a.noData=d.noData);l.isDefined(d.noDataInterpretation)&&(a.noDataInterpretation=d.noDataInterpretation);l.isDefined(d.interpolation)&&(a.interpolation=d.interpolation);var m={imageServiceParameters:a,opacity:d.opacity,visible:d.visibility};
l.isDefined(d.mapLayerId)&&(m.id=d.mapLayerId);l.isDefined(d.minScale)&&(m.minScale=d.minScale);l.isDefined(d.maxScale)&&(m.maxScale=d.maxScale);l.isDefined(d.refreshInterval)&&(m.refreshInterval=d.refreshInterval);l.isDefined(d.resourceInfo)&&(m.resourceInfo=d.resourceInfo);var f=this,k,p;f._readRestInfo(e).then(function(q){var u=null;if(q&&q.tileInfo&&q.singleFusedMapCache)return u="Raster"===q.cacheType?new X(e,{id:c}):new H(e,{id:c}),f._waitForLayer(u).then(function(n){p=n});u=new P(f._checkUrl(g),
m);return f._waitForLayer(u).then(function(n){k=n})}).then(function(){if(k){var q=k;d.layerDefinition&&d.layerDefinition.definitionExpression&&q.setDefinitionExpression(d.layerDefinition.definitionExpression,!0);!d.disablePopup&&d.popupInfo&&q.setInfoTemplate(new z(d.popupInfo));b.resolve(q)}else p?b.resolve(p):b.resolve()}).otherwise(function(q){b.reject(q)});return b},_newInfoTemplate:function(a,b){if(a)try{return new z({description:a.description,title:a.title,showAttachments:a.showAttachments,
fieldInfos:a.fieldInfos,mediaInfos:a.mediaInfos})}catch(c){console.error(c)}a=new ea;l.isDefined(b)&&a.setTitle(b);return a},_newKMLLayer:function(){var a={id:this._generateLayerId()};a=new T(this.serviceUrl,a);return this._waitForLayer(a)},_newMapServiceLayer:function(a){var b=this,c=new t,e=this.serviceUrl,g=this._generateLayerId();w({url:e,content:{f:"json"},handleAs:"json",callbackParamName:"callback"},{}).then(function(d){var h=null;h={id:g};if(d.tileInfo)h=new H(e,h);else if(d&&d.supportedImageFormatTypes&&
-1!==d.supportedImageFormatTypes.indexOf("PNG32")&&(h.imageParameters=new R,h.imageParameters.format="png32"),h=new O(e,h),a&&a.layers&&0<a.layers.length){var m=[],f,k=[],p,q=[],u;r.forEach(a.layers,function(n){n.layerDefinition&&n.layerDefinition.definitionExpression&&(m[n.id]=n.layerDefinition.definitionExpression);if(n.layerDefinition&&n.layerDefinition.source){f=null;u=n.layerDefinition.source;if("mapLayer"===u.type){var v=r.filter(d.layers,function(x){return x.id===u.mapLayerId});v.length&&(f=
B.mixin(v[0],n))}else f=B.mixin({},n);f&&(f.source=u,delete f.popupInfo,f=new Q(f),a.visibleLayers&&(v="string"===typeof a.visibleLayers?a.visibleLayers.split(","):a.visibleLayers,-1<r.indexOf(v,n.id)?f.defaultVisibility=!0:f.defaultVisibility=!1),k.push(f))}n.layerDefinition&&n.layerDefinition.source&&n.layerDefinition.drawingInfo&&(p=new U(n.layerDefinition.drawingInfo),q[n.id]=p)});0<m.length&&h.setLayerDefinitions(m);0<k.length&&(h.setDynamicLayerInfos(k,!0),0<q.length&&h.setLayerDrawingOptions(q,
!0))}b._waitForLayer(h).then(function(n){var v=null;r.forEach(n.layerInfos,function(x){var A=null;a&&r.some(a.layers,function(K){if(x.id===K.id)return A=K,!0});var D=null;A&&A.popupInfo&&(D=A.popupInfo);D&&(null===v&&(v={}),v[x.id]={infoTemplate:b._newInfoTemplate(D,x.name)})});null===n.infoTemplates&&(v?n.infoTemplates=v:b._setDynamicLayerInfoTemplates(n));c.resolve(n)},function(n){c.reject(n)})},function(d){c.reject(d)});return c},_getVisibleFeatureLayers:function(a,b){if(!a||!b||0===b.length)return[];
b=","+b+",";var c=[],e,g=",";for(e=0;e<a.length;e++)if(null!==a[e].subLayerIds){if(-1===b.indexOf(","+a[e].id+",")||-1<g.indexOf(","+a[e].id+","))g+=a[e].subLayerIds.toString()+","}else-1<b.indexOf(","+a[e].id+",")&&-1===g.indexOf(","+a[e].id+",")&&c.push(a[e].id);return c},_newPopupInfo:function(a,b){if(a&&a.fields){var c={title:a.name,fieldInfos:[],description:null,showAttachments:!0,mediaInfos:[]};"string"===typeof b&&0<b.length&&(c.title=b);r.forEach(a.fields,function(e){var g=ha.getDefaultPortalFieldInfo(e);
g.visible=!0;g.isEditable=e.editable;c.fieldInfos.push(g)});return c}return null},_newVectorTileLayer:function(){var a=this,b=new t,c={},e=this.serviceUrl,g=this._generateLayerId();"string"===typeof e&&0<e.length?this._checkVectorTileUrl(e,c).then(function(d){"string"===typeof d&&0<d.length?(d=a._checkMixedContent(d),d=new Z(d,{id:g,opacity:1,visible:!0}),a._waitForLayer(d).then(function(h){b.resolve(h)},function(h){b.reject(h)})):b.resolve(null)},function(d){b.reject(d)}):b.resolve(null);return b},
_newWFSLayer:function(a){var b=new t;try{var c=this._generateLayerId();if(a&&a.wfsInfo&&a.layerDefinition)var e={id:c,mode:a.mode,showLabels:!0,title:a.title,url:this._checkMixedContent(a.url),customParameters:a.wfsInfo.customParameters,maxFeatures:a.wfsInfo.maxFeatures,name:a.wfsInfo.name,swapXY:a.wfsInfo.swapXY,version:a.wfsInfo.version,geometryType:a.layerDefinition.geometryType,labelingInfo:a.layerDefinition.drawingInfo.labelingInfo};else{var g=this.serviceUrl;g?G.loadWFSByUrl(b,map,this,g,c,
!1):b.reject(Error("Error adding WFS, no URL"));return b}var d=new aa,h=d.on("error",function(m){h&&h.remove();b.reject(m.error)});d.fromJson(e,function(){try{h&&h.remove();if(a&&a.wfsInfo&&a.layerDefinition){l.isDefined(a.opacity)&&d.setOpacity(a.opacity);l.isDefined(a.visibility)&&d.setVisibility(a.visibility);(a.minScale||a.maxScale)&&d.setScaleRange(a.minScale,a.maxScale);var m=a.layerDefinition.drawingInfo;m&&m.renderer&&(d.renderer=J.fromJson(m.renderer,{geometryType:e.geometryType}));a.popupInfo&&
d.setInfoTemplate(new z(a.popupInfo))}b.resolve(d)}catch(f){console.error("Error adding WFS",f),b.reject(ex)}})}catch(m){console.error("Error adding WFS",m),b.reject(m)}return b},_newWMSLayer:function(a){var b=this,c=this.item,e=!1,g=null,d={id:this._generateLayerId()};if(a){var h=[],m=[];r.forEach(a.layers,function(f){e=!0;m.push(new ca({name:f.name,title:f.title,legendURL:f.legendURL,queryable:f.queryable,showPopup:f.showPopup}));h.push(f.name)},this);a.visibleLayers&&(h=a.visibleLayers);d={customLayerParameters:a.customLayerParameters,
customParameters:a.customParameters,layerInfos:m,version:a.version,maxWidth:a.maxWidth,maxHeight:a.maxHeight,featureInfoFormat:a.featureInfoFormat,getFeatureInfoURL:a.featureInfoUrl,getMapURL:a.mapUrl,spatialReferences:a.spatialReferences,title:a.title,copyright:a.copyright,minScale:a.minScale||0,maxScale:a.maxScale||0,format:a.format};c&&c.extent&&(c=new C(c.extent[0][0],c.extent[0][1],c.extent[1][0],c.extent[1][1],new fa({wkid:4326})),d.extent=c);a.spatialReferences&&0<a.spatialReferences.length&&
(g=a.spatialReferences[0]);d={id:this._generateLayerId(),visibleLayers:h,format:"png",transparent:a.firstLayer?!1:!0,opacity:a.opacity,visible:null!==a.visibility?a.visibility:!0,resourceInfo:d,refreshInterval:a.refreshInterval}}a=new ba(this.serviceUrl,d);a=this._waitForLayer(a);a.then(function(f){e||b._setWMSVisibleLayers(f);g&&f.spatialReference&&(f.spatialReference.wkid=g)});return a},_newWMTSLayer:function(a){if(a){var b=new da(a.templateUrl,{id:this._generateLayerId(),visible:null!==a.visibility?
a.visibility:!0,opacity:a.opacity,copyright:a.copyright,fullExtent:a.fullExtent&&new C(a.fullExtent),initialExtent:a.fullExtent&&new C(a.fullExtent),subDomains:a.subDomains,tileInfo:a.tileInfo?new Y(a.tileInfo):null,refreshInterval:a.refreshInterval,wmtsInfo:a.wmtsInfo});if(l.isDefined(a.minScale)||l.isDefined(a.maxScale))b.loaded?b.setScaleRange(a.minScale,a.maxScale):M.connect(b,"onLoad",function(){b.setScaleRange(a.minScale,a.maxScale)});return this._waitForLayer(b)}var c=new t;c.resolve();return c},
_processFeatureLayer:function(a,b,c){var e=this,g=F.search.featureLayerTitlePattern,d=null;c&&c.layers&&0<c.layers.length?(r.some(c.layers,function(h){var m=!1;if(h.id===a.layerId){if(h.popupInfo){var f=h.popupInfo;f=y.parse(y.stringify(f));f=new z(f);a.setInfoTemplate(f);m=!0}l.isDefined(h.showLabels)&&a.setShowLabels(h.showLabels);l.isDefined(h.refreshInterval)&&a.setRefreshInterval(h.refreshInterval);l.isDefined(h.showLegend)&&console.log("");l.isDefined(h.timeAnimation)&&!1===h.timeAnimation&&
console.log("");if(f=h.layerDefinition){f.definitionExpression&&a.setDefinitionExpression(f.definitionExpression);f.displayField&&a.displayField(f.displayField);if(f.drawingInfo){if(f.drawingInfo.renderer){var k=y.parse(y.stringify(f.drawingInfo.renderer));var p=J.fromJson(k);k.type&&"classBreaks"===k.type&&(p.isMaxInclusive=!0);a.setRenderer(p)}l.isDefined(f.drawingInfo.transparency)&&a.setOpacity(1-f.drawingInfo.transparency/100)}l.isDefined(f.minScale)&&a.setMinScale(f.minScale);l.isDefined(f.maxScale)&&
a.setMaxScale(f.maxScale);l.isDefined(f.defaultVisibility)&&!1===f.defaultVisibility&&a.setVisibility(!1)}m||e._setFeatureLayerInfoTemplate(a,h.popupInfo);d={url:a.url,id:a.id,itemId:b.id,title:e._makeFeatureLayerTitle(g,b.title,a.name)};return!0}}),d||(d={url:a.url,id:a.id,itemId:b.id,title:e._makeFeatureLayerTitle(g,b.title,a.name)},e._setFeatureLayerInfoTemplate(a,null,d.title))):(d={url:a.url,id:a.id,itemId:b.id,title:e._makeFeatureLayerTitle(g,b.title,a.name)},e._setFeatureLayerInfoTemplate(a,
null,d.title));return d},_readItemJsonData:function(){return w({url:this.itemUrl+"/data",content:{f:"json"},handleAs:"json"},{})},_readRestInfo:function(a){return w({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"},{})},_setDynamicLayerInfoTemplates:function(a){var b=this,c=null,e=[],g=function(d){var h=b._readRestInfo(a.url+"/"+d.id);h.then(function(m){try{var f=b._newPopupInfo(m);f&&(c[d.id]={infoTemplate:b._newInfoTemplate(f)})}catch(k){console.warn("Error setting popup."),
console.error(k)}});return h};null===a.infoTemplates&&r.forEach(a.layerInfos,function(d){null===c&&(c={});d.subLayerIds||e.push(g(d))});0<e.length&&E(e).then(function(){c&&(a.infoTemplates=c)}).otherwise(function(d){console.warn("Error reading sublayers.");console.error(d)})},_setFeatureLayerInfoTemplate:function(a,b,c){b||(b=this._newPopupInfo(a,c));b=this._newInfoTemplate(b,c);a.setInfoTemplate(b)},_setWMSVisibleLayers:function(a){var b=[];a&&(r.some(a.layerInfos,function(c){if("string"===typeof c.name&&
0<c.name.length)if(10>b.length)b.push(c.name);else return!0}),10>=b.length&&a.setVisibleLayers(b))},_waitForLayer:function(a){var b=new t,c=[];if(a.loaded)return b.resolve(a),b;if(a.loadError)return b.reject(a.loadError),b;var e=function(){r.forEach(c,function(g){g.remove()})};c.push(a.on("load",function(g){e();b.resolve(g.layer)}));c.push(a.on("error",function(g){e();g=g.error;try{g.message&&-1!==g.message.indexOf("Unable to complete")?(console.warn("layerAccessError",g),b.reject(Error(F.search.layerInaccessible))):
b.reject(g)}catch(d){b.reject(g)}}));return b}})});